// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service_gate.proto

package lbtproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BindClientInfo struct {
	Caddr string `protobuf:"bytes,1,opt,name=caddr,proto3" json:"caddr,omitempty"`
	Saddr string `protobuf:"bytes,2,opt,name=saddr,proto3" json:"saddr,omitempty"`
}

func (m *BindClientInfo) Reset()         { *m = BindClientInfo{} }
func (m *BindClientInfo) String() string { return proto.CompactTextString(m) }
func (*BindClientInfo) ProtoMessage()    {}
func (*BindClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff9168d185c861b5, []int{0}
}
func (m *BindClientInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BindClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BindClientInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BindClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindClientInfo.Merge(m, src)
}
func (m *BindClientInfo) XXX_Size() int {
	return m.Size()
}
func (m *BindClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BindClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BindClientInfo proto.InternalMessageInfo

func (m *BindClientInfo) GetCaddr() string {
	if m != nil {
		return m.Caddr
	}
	return ""
}

func (m *BindClientInfo) GetSaddr() string {
	if m != nil {
		return m.Saddr
	}
	return ""
}

type Filter struct {
	Attr string `protobuf:"bytes,1,opt,name=attr,proto3" json:"attr,omitempty"`
	Op   string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Val  int32  `protobuf:"varint,3,opt,name=val,proto3" json:"val,omitempty"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff9168d185c861b5, []int{1}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return m.Size()
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetAttr() string {
	if m != nil {
		return m.Attr
	}
	return ""
}

func (m *Filter) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *Filter) GetVal() int32 {
	if m != nil {
		return m.Val
	}
	return 0
}

type FilterData struct {
	Id   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data map[string]int32 `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (m *FilterData) Reset()         { *m = FilterData{} }
func (m *FilterData) String() string { return proto.CompactTextString(m) }
func (*FilterData) ProtoMessage()    {}
func (*FilterData) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff9168d185c861b5, []int{2}
}
func (m *FilterData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FilterData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FilterData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FilterData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterData.Merge(m, src)
}
func (m *FilterData) XXX_Size() int {
	return m.Size()
}
func (m *FilterData) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterData.DiscardUnknown(m)
}

var xxx_messageInfo_FilterData proto.InternalMessageInfo

func (m *FilterData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FilterData) GetData() map[string]int32 {
	if m != nil {
		return m.Data
	}
	return nil
}

type FilterMsg struct {
	Method  string    `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Params  []byte    `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	Filters []*Filter `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (m *FilterMsg) Reset()         { *m = FilterMsg{} }
func (m *FilterMsg) String() string { return proto.CompactTextString(m) }
func (*FilterMsg) ProtoMessage()    {}
func (*FilterMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff9168d185c861b5, []int{3}
}
func (m *FilterMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FilterMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FilterMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FilterMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterMsg.Merge(m, src)
}
func (m *FilterMsg) XXX_Size() int {
	return m.Size()
}
func (m *FilterMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FilterMsg proto.InternalMessageInfo

func (m *FilterMsg) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *FilterMsg) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *FilterMsg) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func init() {
	proto.RegisterType((*BindClientInfo)(nil), "lbtproto.BindClientInfo")
	proto.RegisterType((*Filter)(nil), "lbtproto.Filter")
	proto.RegisterType((*FilterData)(nil), "lbtproto.FilterData")
	proto.RegisterMapType((map[string]int32)(nil), "lbtproto.FilterData.DataEntry")
	proto.RegisterType((*FilterMsg)(nil), "lbtproto.FilterMsg")
}

func init() { proto.RegisterFile("service_gate.proto", fileDescriptor_ff9168d185c861b5) }

var fileDescriptor_ff9168d185c861b5 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x7b, 0x4e, 0x53, 0x9a, 0xd7, 0x24, 0x84, 0x23, 0x44, 0x51, 0x06, 0x2b, 0xca, 0x14,
	0x31, 0x44, 0x22, 0x08, 0xa5, 0x85, 0xd2, 0x21, 0x50, 0x50, 0x87, 0x2e, 0x46, 0x62, 0xb5, 0x2e,
	0xf6, 0xd5, 0xb5, 0x70, 0xee, 0x8c, 0xef, 0x12, 0x94, 0x8d, 0x11, 0xb6, 0x7e, 0x07, 0xbe, 0x0c,
	0x63, 0x47, 0x46, 0x94, 0x7c, 0x11, 0x74, 0x77, 0x76, 0x4c, 0x9d, 0x0c, 0x34, 0x13, 0x4b, 0x74,
	0xef, 0xef, 0xf7, 0xbb, 0xf7, 0xbf, 0xbc, 0x3f, 0x60, 0x41, 0x93, 0x79, 0xe8, 0x51, 0x37, 0x20,
	0x92, 0x0e, 0xe2, 0x84, 0x4b, 0x8e, 0x0f, 0xa3, 0x89, 0xd4, 0xa7, 0x4e, 0xd5, 0xe3, 0xd3, 0x29,
	0x67, 0x46, 0xef, 0x9d, 0x42, 0x7d, 0x1c, 0x32, 0xff, 0x4d, 0x14, 0x52, 0x26, 0x2f, 0xd8, 0x15,
	0xc7, 0x4d, 0x28, 0x7b, 0xc4, 0xf7, 0x93, 0x36, 0xea, 0xa2, 0x7e, 0xc5, 0x31, 0x85, 0x52, 0x85,
	0x56, 0x2d, 0xa3, 0xea, 0xa2, 0x77, 0x06, 0x07, 0xef, 0xc2, 0x48, 0xd2, 0x04, 0x63, 0xd8, 0x27,
	0x52, 0x66, 0x90, 0x3e, 0xe3, 0x3a, 0x58, 0x3c, 0x4e, 0x01, 0x8b, 0xc7, 0xb8, 0x01, 0xa5, 0x39,
	0x89, 0xda, 0xa5, 0x2e, 0xea, 0x97, 0x1d, 0x75, 0xec, 0x7d, 0x47, 0x00, 0xe6, 0x82, 0xb7, 0x44,
	0x12, 0x05, 0x84, 0x7e, 0x7a, 0x85, 0x15, 0xfa, 0x78, 0x08, 0xfb, 0x3e, 0x91, 0xa4, 0x6d, 0x75,
	0x4b, 0xfd, 0xa3, 0xa1, 0x3d, 0xc8, 0xde, 0x30, 0xc8, 0x99, 0x81, 0xfa, 0x39, 0x67, 0x32, 0x59,
	0x38, 0xba, 0xb7, 0x33, 0x82, 0xca, 0x5a, 0x52, 0x13, 0x3f, 0xd1, 0x45, 0x7a, 0xa3, 0x3a, 0xaa,
	0x77, 0xcc, 0x49, 0x34, 0xa3, 0xda, 0x56, 0xd9, 0x31, 0xc5, 0x4b, 0xeb, 0x18, 0xf5, 0x02, 0xa8,
	0x98, 0x6b, 0x2f, 0x45, 0x80, 0x5b, 0x70, 0x30, 0xa5, 0xf2, 0x9a, 0x67, 0x6e, 0xd2, 0x4a, 0xe9,
	0x31, 0x49, 0xc8, 0x54, 0x68, 0xbe, 0xea, 0xa4, 0x15, 0x7e, 0x0a, 0x0f, 0xae, 0x34, 0x2c, 0xda,
	0x25, 0x6d, 0xb6, 0x51, 0x34, 0xeb, 0x64, 0x0d, 0xc3, 0x6f, 0x65, 0xa8, 0x5e, 0x7c, 0x30, 0x2b,
	0x7a, 0x4f, 0x24, 0xc5, 0x27, 0xd0, 0x48, 0x68, 0x10, 0x0a, 0x49, 0x13, 0x37, 0x5d, 0x1d, 0x7e,
	0x92, 0xf3, 0x69, 0xab, 0x5a, 0x4e, 0xa7, 0x9e, 0xcb, 0x1f, 0x79, 0xe8, 0xe3, 0x11, 0x1c, 0x4d,
	0x42, 0xe6, 0xbb, 0x9e, 0xde, 0x1f, 0x6e, 0xe7, 0x9f, 0xef, 0x6e, 0x75, 0x03, 0x3c, 0x81, 0xda,
	0x8c, 0xed, 0x86, 0xbe, 0x82, 0x87, 0x59, 0xc0, 0x12, 0xfa, 0x79, 0x46, 0xc5, 0x1d, 0x38, 0x75,
	0xeb, 0x98, 0x2f, 0x5b, 0x0c, 0xd7, 0x72, 0x38, 0x8e, 0x16, 0xb8, 0xb5, 0x05, 0x8d, 0xa3, 0xc5,
	0x06, 0x78, 0x06, 0x4d, 0xe3, 0xd4, 0xdd, 0x8d, 0x7f, 0x01, 0x35, 0x2f, 0xa1, 0x44, 0x52, 0x97,
	0x32, 0x19, 0xca, 0x05, 0x6e, 0xe6, 0x0d, 0xe7, 0x5a, 0x51, 0xb1, 0xd9, 0xc0, 0x9e, 0x01, 0x98,
	0x7e, 0x77, 0x2a, 0x02, 0xfc, 0xb8, 0xc8, 0x5c, 0x8a, 0x60, 0x03, 0x39, 0x86, 0x47, 0xa9, 0xd3,
	0xfb, 0x92, 0xa7, 0xd0, 0x5c, 0x07, 0xc1, 0xa4, 0xc5, 0x55, 0x99, 0xfe, 0xdb, 0x6a, 0x9e, 0xfc,
	0x6d, 0x56, 0x53, 0xa8, 0x30, 0x70, 0x1d, 0xeb, 0x22, 0x32, 0xfc, 0x51, 0x82, 0xc3, 0x2c, 0x8a,
	0x78, 0x04, 0xf5, 0xf5, 0x74, 0xf3, 0xdf, 0xfe, 0x63, 0x08, 0x5f, 0xaf, 0x1f, 0xec, 0x87, 0xc2,
	0xe3, 0x8c, 0x51, 0xef, 0xff, 0xcf, 0xd3, 0x18, 0x5a, 0x1b, 0x79, 0xba, 0xef, 0xf0, 0x1d, 0xc2,
	0x31, 0x84, 0x46, 0x36, 0x4f, 0x5c, 0xcf, 0xa4, 0xcf, 0xbf, 0x30, 0x5c, 0xe8, 0x29, 0x32, 0x63,
	0xfb, 0xe7, 0xd2, 0x46, 0xb7, 0x4b, 0x1b, 0xfd, 0x5e, 0xda, 0xe8, 0x66, 0x65, 0xef, 0xdd, 0xae,
	0xec, 0xbd, 0x5f, 0x2b, 0x7b, 0xef, 0x2b, 0x42, 0x37, 0x08, 0x4d, 0x0e, 0x74, 0xef, 0xf3, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xee, 0x06, 0xc9, 0x9f, 0xf8, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IServiceGateClient is the client API for IServiceGate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IServiceGateClient interface {
	RegisterService(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Void, error)
	BindClient(ctx context.Context, in *BindClientInfo, opts ...grpc.CallOption) (*Void, error)
	UnbindClient(ctx context.Context, in *BindClientInfo, opts ...grpc.CallOption) (*Void, error)
	ServiceRequest(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*Void, error)
	ServiceReply(ctx context.Context, in *ServiceReply, opts ...grpc.CallOption) (*Void, error)
	ClientServiceReply(ctx context.Context, in *ServiceReply, opts ...grpc.CallOption) (*Void, error)
	CreateEntity(ctx context.Context, in *EntityData, opts ...grpc.CallOption) (*Void, error)
	EntityMsg(ctx context.Context, in *EntityMsg, opts ...grpc.CallOption) (*Void, error)
	ClientEntityMsg(ctx context.Context, in *EntityMsg, opts ...grpc.CallOption) (*Void, error)
	RegisterFilterData(ctx context.Context, in *FilterData, opts ...grpc.CallOption) (*Void, error)
	FilterMsg(ctx context.Context, in *FilterMsg, opts ...grpc.CallOption) (*Void, error)
}

type iServiceGateClient struct {
	cc *grpc.ClientConn
}

func NewIServiceGateClient(cc *grpc.ClientConn) IServiceGateClient {
	return &iServiceGateClient{cc}
}

func (c *iServiceGateClient) RegisterService(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/register_service", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) BindClient(ctx context.Context, in *BindClientInfo, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/bind_client", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) UnbindClient(ctx context.Context, in *BindClientInfo, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/unbind_client", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) ServiceRequest(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/service_request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) ServiceReply(ctx context.Context, in *ServiceReply, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/service_reply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) ClientServiceReply(ctx context.Context, in *ServiceReply, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/client_service_reply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) CreateEntity(ctx context.Context, in *EntityData, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/create_entity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) EntityMsg(ctx context.Context, in *EntityMsg, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/entity_msg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) ClientEntityMsg(ctx context.Context, in *EntityMsg, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/client_entity_msg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) RegisterFilterData(ctx context.Context, in *FilterData, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/register_filter_data", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceGateClient) FilterMsg(ctx context.Context, in *FilterMsg, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IServiceGate/filter_msg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IServiceGateServer is the server API for IServiceGate service.
type IServiceGateServer interface {
	RegisterService(context.Context, *ServiceInfo) (*Void, error)
	BindClient(context.Context, *BindClientInfo) (*Void, error)
	UnbindClient(context.Context, *BindClientInfo) (*Void, error)
	ServiceRequest(context.Context, *ServiceRequest) (*Void, error)
	ServiceReply(context.Context, *ServiceReply) (*Void, error)
	ClientServiceReply(context.Context, *ServiceReply) (*Void, error)
	CreateEntity(context.Context, *EntityData) (*Void, error)
	EntityMsg(context.Context, *EntityMsg) (*Void, error)
	ClientEntityMsg(context.Context, *EntityMsg) (*Void, error)
	RegisterFilterData(context.Context, *FilterData) (*Void, error)
	FilterMsg(context.Context, *FilterMsg) (*Void, error)
}

// UnimplementedIServiceGateServer can be embedded to have forward compatible implementations.
type UnimplementedIServiceGateServer struct {
}

func (*UnimplementedIServiceGateServer) RegisterService(ctx context.Context, req *ServiceInfo) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterService not implemented")
}
func (*UnimplementedIServiceGateServer) BindClient(ctx context.Context, req *BindClientInfo) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindClient not implemented")
}
func (*UnimplementedIServiceGateServer) UnbindClient(ctx context.Context, req *BindClientInfo) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbindClient not implemented")
}
func (*UnimplementedIServiceGateServer) ServiceRequest(ctx context.Context, req *ServiceRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceRequest not implemented")
}
func (*UnimplementedIServiceGateServer) ServiceReply(ctx context.Context, req *ServiceReply) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceReply not implemented")
}
func (*UnimplementedIServiceGateServer) ClientServiceReply(ctx context.Context, req *ServiceReply) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientServiceReply not implemented")
}
func (*UnimplementedIServiceGateServer) CreateEntity(ctx context.Context, req *EntityData) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEntity not implemented")
}
func (*UnimplementedIServiceGateServer) EntityMsg(ctx context.Context, req *EntityMsg) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntityMsg not implemented")
}
func (*UnimplementedIServiceGateServer) ClientEntityMsg(ctx context.Context, req *EntityMsg) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientEntityMsg not implemented")
}
func (*UnimplementedIServiceGateServer) RegisterFilterData(ctx context.Context, req *FilterData) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterFilterData not implemented")
}
func (*UnimplementedIServiceGateServer) FilterMsg(ctx context.Context, req *FilterMsg) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterMsg not implemented")
}

func RegisterIServiceGateServer(s *grpc.Server, srv IServiceGateServer) {
	s.RegisterService(&_IServiceGate_serviceDesc, srv)
}

func _IServiceGate_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).RegisterService(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_BindClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).BindClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/BindClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).BindClient(ctx, req.(*BindClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_UnbindClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).UnbindClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/UnbindClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).UnbindClient(ctx, req.(*BindClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_ServiceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).ServiceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/ServiceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).ServiceRequest(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_ServiceReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).ServiceReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/ServiceReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).ServiceReply(ctx, req.(*ServiceReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_ClientServiceReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).ClientServiceReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/ClientServiceReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).ClientServiceReply(ctx, req.(*ServiceReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_CreateEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).CreateEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/CreateEntity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).CreateEntity(ctx, req.(*EntityData))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_EntityMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).EntityMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/EntityMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).EntityMsg(ctx, req.(*EntityMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_ClientEntityMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).ClientEntityMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/ClientEntityMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).ClientEntityMsg(ctx, req.(*EntityMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_RegisterFilterData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).RegisterFilterData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/RegisterFilterData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).RegisterFilterData(ctx, req.(*FilterData))
	}
	return interceptor(ctx, in, info, handler)
}

func _IServiceGate_FilterMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceGateServer).FilterMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IServiceGate/FilterMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceGateServer).FilterMsg(ctx, req.(*FilterMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _IServiceGate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lbtproto.IServiceGate",
	HandlerType: (*IServiceGateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register_service",
			Handler:    _IServiceGate_RegisterService_Handler,
		},
		{
			MethodName: "bind_client",
			Handler:    _IServiceGate_BindClient_Handler,
		},
		{
			MethodName: "unbind_client",
			Handler:    _IServiceGate_UnbindClient_Handler,
		},
		{
			MethodName: "service_request",
			Handler:    _IServiceGate_ServiceRequest_Handler,
		},
		{
			MethodName: "service_reply",
			Handler:    _IServiceGate_ServiceReply_Handler,
		},
		{
			MethodName: "client_service_reply",
			Handler:    _IServiceGate_ClientServiceReply_Handler,
		},
		{
			MethodName: "create_entity",
			Handler:    _IServiceGate_CreateEntity_Handler,
		},
		{
			MethodName: "entity_msg",
			Handler:    _IServiceGate_EntityMsg_Handler,
		},
		{
			MethodName: "client_entity_msg",
			Handler:    _IServiceGate_ClientEntityMsg_Handler,
		},
		{
			MethodName: "register_filter_data",
			Handler:    _IServiceGate_RegisterFilterData_Handler,
		},
		{
			MethodName: "filter_msg",
			Handler:    _IServiceGate_FilterMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_gate.proto",
}

// IServiceClient is the client API for IService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IServiceClient interface {
	RegisterReply(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Void, error)
	ClientDisconnect(ctx context.Context, in *BindClientInfo, opts ...grpc.CallOption) (*Void, error)
	ServiceRequest(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*Void, error)
	ServiceReply(ctx context.Context, in *ServiceReply, opts ...grpc.CallOption) (*Void, error)
	ClientServiceRequest(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*Void, error)
	EntityMsg(ctx context.Context, in *EntityMsg, opts ...grpc.CallOption) (*Void, error)
	ServiceShutdown(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
}

type iServiceClient struct {
	cc *grpc.ClientConn
}

func NewIServiceClient(cc *grpc.ClientConn) IServiceClient {
	return &iServiceClient{cc}
}

func (c *iServiceClient) RegisterReply(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IService/register_reply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceClient) ClientDisconnect(ctx context.Context, in *BindClientInfo, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IService/client_disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceClient) ServiceRequest(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IService/service_request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceClient) ServiceReply(ctx context.Context, in *ServiceReply, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IService/service_reply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceClient) ClientServiceRequest(ctx context.Context, in *ServiceRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IService/client_service_request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceClient) EntityMsg(ctx context.Context, in *EntityMsg, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IService/entity_msg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iServiceClient) ServiceShutdown(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/lbtproto.IService/service_shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IServiceServer is the server API for IService service.
type IServiceServer interface {
	RegisterReply(context.Context, *ServiceInfo) (*Void, error)
	ClientDisconnect(context.Context, *BindClientInfo) (*Void, error)
	ServiceRequest(context.Context, *ServiceRequest) (*Void, error)
	ServiceReply(context.Context, *ServiceReply) (*Void, error)
	ClientServiceRequest(context.Context, *ServiceRequest) (*Void, error)
	EntityMsg(context.Context, *EntityMsg) (*Void, error)
	ServiceShutdown(context.Context, *Void) (*Void, error)
}

// UnimplementedIServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIServiceServer struct {
}

func (*UnimplementedIServiceServer) RegisterReply(ctx context.Context, req *ServiceInfo) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterReply not implemented")
}
func (*UnimplementedIServiceServer) ClientDisconnect(ctx context.Context, req *BindClientInfo) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientDisconnect not implemented")
}
func (*UnimplementedIServiceServer) ServiceRequest(ctx context.Context, req *ServiceRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceRequest not implemented")
}
func (*UnimplementedIServiceServer) ServiceReply(ctx context.Context, req *ServiceReply) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceReply not implemented")
}
func (*UnimplementedIServiceServer) ClientServiceRequest(ctx context.Context, req *ServiceRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientServiceRequest not implemented")
}
func (*UnimplementedIServiceServer) EntityMsg(ctx context.Context, req *EntityMsg) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntityMsg not implemented")
}
func (*UnimplementedIServiceServer) ServiceShutdown(ctx context.Context, req *Void) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceShutdown not implemented")
}

func RegisterIServiceServer(s *grpc.Server, srv IServiceServer) {
	s.RegisterService(&_IService_serviceDesc, srv)
}

func _IService_RegisterReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceServer).RegisterReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IService/RegisterReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceServer).RegisterReply(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _IService_ClientDisconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceServer).ClientDisconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IService/ClientDisconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceServer).ClientDisconnect(ctx, req.(*BindClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _IService_ServiceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceServer).ServiceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IService/ServiceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceServer).ServiceRequest(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IService_ServiceReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceServer).ServiceReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IService/ServiceReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceServer).ServiceReply(ctx, req.(*ServiceReply))
	}
	return interceptor(ctx, in, info, handler)
}

func _IService_ClientServiceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceServer).ClientServiceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IService/ClientServiceRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceServer).ClientServiceRequest(ctx, req.(*ServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IService_EntityMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceServer).EntityMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IService/EntityMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceServer).EntityMsg(ctx, req.(*EntityMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _IService_ServiceShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IServiceServer).ServiceShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lbtproto.IService/ServiceShutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IServiceServer).ServiceShutdown(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _IService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lbtproto.IService",
	HandlerType: (*IServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register_reply",
			Handler:    _IService_RegisterReply_Handler,
		},
		{
			MethodName: "client_disconnect",
			Handler:    _IService_ClientDisconnect_Handler,
		},
		{
			MethodName: "service_request",
			Handler:    _IService_ServiceRequest_Handler,
		},
		{
			MethodName: "service_reply",
			Handler:    _IService_ServiceReply_Handler,
		},
		{
			MethodName: "client_service_request",
			Handler:    _IService_ClientServiceRequest_Handler,
		},
		{
			MethodName: "entity_msg",
			Handler:    _IService_EntityMsg_Handler,
		},
		{
			MethodName: "service_shutdown",
			Handler:    _IService_ServiceShutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_gate.proto",
}

func (m *BindClientInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BindClientInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BindClientInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Saddr) > 0 {
		i -= len(m.Saddr)
		copy(dAtA[i:], m.Saddr)
		i = encodeVarintServiceGate(dAtA, i, uint64(len(m.Saddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Caddr) > 0 {
		i -= len(m.Caddr)
		copy(dAtA[i:], m.Caddr)
		i = encodeVarintServiceGate(dAtA, i, uint64(len(m.Caddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Filter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Filter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Filter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Val != 0 {
		i = encodeVarintServiceGate(dAtA, i, uint64(m.Val))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Op) > 0 {
		i -= len(m.Op)
		copy(dAtA[i:], m.Op)
		i = encodeVarintServiceGate(dAtA, i, uint64(len(m.Op)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Attr) > 0 {
		i -= len(m.Attr)
		copy(dAtA[i:], m.Attr)
		i = encodeVarintServiceGate(dAtA, i, uint64(len(m.Attr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FilterData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FilterData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FilterData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		for k := range m.Data {
			v := m.Data[k]
			baseI := i
			i = encodeVarintServiceGate(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintServiceGate(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintServiceGate(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintServiceGate(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FilterMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FilterMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FilterMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Filters) > 0 {
		for iNdEx := len(m.Filters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Filters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintServiceGate(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Params) > 0 {
		i -= len(m.Params)
		copy(dAtA[i:], m.Params)
		i = encodeVarintServiceGate(dAtA, i, uint64(len(m.Params)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Method) > 0 {
		i -= len(m.Method)
		copy(dAtA[i:], m.Method)
		i = encodeVarintServiceGate(dAtA, i, uint64(len(m.Method)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintServiceGate(dAtA []byte, offset int, v uint64) int {
	offset -= sovServiceGate(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BindClientInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Caddr)
	if l > 0 {
		n += 1 + l + sovServiceGate(uint64(l))
	}
	l = len(m.Saddr)
	if l > 0 {
		n += 1 + l + sovServiceGate(uint64(l))
	}
	return n
}

func (m *Filter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Attr)
	if l > 0 {
		n += 1 + l + sovServiceGate(uint64(l))
	}
	l = len(m.Op)
	if l > 0 {
		n += 1 + l + sovServiceGate(uint64(l))
	}
	if m.Val != 0 {
		n += 1 + sovServiceGate(uint64(m.Val))
	}
	return n
}

func (m *FilterData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovServiceGate(uint64(l))
	}
	if len(m.Data) > 0 {
		for k, v := range m.Data {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovServiceGate(uint64(len(k))) + 1 + sovServiceGate(uint64(v))
			n += mapEntrySize + 1 + sovServiceGate(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *FilterMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovServiceGate(uint64(l))
	}
	l = len(m.Params)
	if l > 0 {
		n += 1 + l + sovServiceGate(uint64(l))
	}
	if len(m.Filters) > 0 {
		for _, e := range m.Filters {
			l = e.Size()
			n += 1 + l + sovServiceGate(uint64(l))
		}
	}
	return n
}

func sovServiceGate(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozServiceGate(x uint64) (n int) {
	return sovServiceGate(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BindClientInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServiceGate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BindClientInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BindClientInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Caddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Caddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Saddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Saddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServiceGate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServiceGate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Filter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServiceGate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Filter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Filter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Op", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Op = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Val", wireType)
			}
			m.Val = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Val |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipServiceGate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServiceGate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FilterData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServiceGate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FilterData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FilterData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServiceGate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServiceGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = make(map[string]int32)
			}
			var mapkey string
			var mapvalue int32
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowServiceGate
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowServiceGate
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthServiceGate
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthServiceGate
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowServiceGate
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipServiceGate(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthServiceGate
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Data[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServiceGate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServiceGate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FilterMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowServiceGate
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FilterMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FilterMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthServiceGate
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthServiceGate
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthServiceGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Params = append(m.Params[:0], dAtA[iNdEx:postIndex]...)
			if m.Params == nil {
				m.Params = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthServiceGate
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthServiceGate
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filters = append(m.Filters, &Filter{})
			if err := m.Filters[len(m.Filters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipServiceGate(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthServiceGate
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipServiceGate(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowServiceGate
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowServiceGate
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthServiceGate
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupServiceGate
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthServiceGate
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthServiceGate        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowServiceGate          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupServiceGate = fmt.Errorf("proto: unexpected end of group")
)
